Intranet_PMO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projetos.urls')),
    path('', include('usuarios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projetos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashborad', views.dashboard, name='dashboard'),
    path('projeto/novo/', views.novo_projeto, name='novo_projeto'),
    path('projeto/<int:projeto_id>/', views.detalhes_projeto, name='detalhes_projeto'),
    path('projeto/<int:projeto_id>/tarefa/', views.nova_tarefa, name='nova_tarefa'),
    path('<int:projeto_id>/upload/', views.upload_arquivo, name='upload_arquivo'),
    path('sobre/', views.sobre, name='sobre'),
    path('contactos/', views.contactos, name='contactos'),
    path('faqs/', views.faqs, name='faqs'),
    ]

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', views.cadastro_view, name='cadastro'),
    path('', views.index, name='index'),
]

usuarios/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Usuario(models.Model):
    nome = models.CharField(max_length=25, null=True)
    nome_usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    password = models.TextField(max_length=12)

    def __str__(self):
        return self.nome

class ConfiguracaoPlataforma(models.Model):
    nome_empresa = models.CharField(max_length=100)
    logotipo = models.ImageField(upload_to='logos/', blank=True, null=True)

    def __str__(self):
        return self.nome_empresa

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from .models import ConfiguracaoPlataforma

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Usuário')
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

class CadastroForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirme a senha', widget=forms.PasswordInput)
    class Meta:
            model = User
            fields = ['username', 'email']

    def clean_password2(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            raise forms.ValidationError('As senhas não coincidem.')
        return self.cleaned_data['password2']


class EditUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username' ,'email', 'password']

class ConfiguracaoForm(ModelForm):
    class Meta:
        model = ConfiguracaoPlataforma
        fields = ['logotipo']

usuarios/views.py
# Create your views here.
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, CadastroForm
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')

    form = LoginForm(data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        login(request, form.get_user())
        return redirect('dashboard')

    return render(request, 'usuarios/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')


def cadastro_view(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('login')
    else:
        form = CadastroForm()
    return render(request, 'usuarios/cadastro.html', {'form': form})


def index(request):
    return render(request, 'usuarios/index.html')

usuarios/templates/usuarios/cadastro.html
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% block content %}
<div class="container" >
  <h2>Cadastro</h2>
<form method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div>
    {{ form.username.label_tag }}<br>
    {{ form.username }}
  </div>
  <div>
    {{ form.email.label_tag }}<br>
    {{ form.email }}
  </div>
  <div>
    {{ form.password.label_tag }}<br>
    {{ form.password }}
  </div>
  <div>
    {{ form.password2.label_tag }}<br>
    {{ form.password2 }}
  </div>
  <button type="submit">Cadastrar</button>
</form>
<p>Já tem conta? <a href="{% url 'login' %}">Entrar</a></p>

</div>


<style>
  body{
    {% comment %} Coloca a imagem de fundo abaixo {% endcomment %}
    {% comment %} background-image: url(/static/background.png); {% endcomment %}
     background-size: 100%;
    background-repeat: no-repeat;
  }
  /*TELA AUTH LOGIN-REGISTRAR*/
  .container{
      text-align: center;
      background-color: white;
      border-radius: 4px;
      padding: 1%;
      margin-left: 30%;
      margin-top: 3%;
      width: 40%;
      padding-bottom: 3%;
      box-shadow: 0 0 5px black;
      background-color: rgba(0, 0, 0, 0.2);

  }
  .container h2{
    color: #002;
      margin-bottom: 5%;
      margin-top: 10%;
  }
  .container input{
      padding: 4px;
      margin: 1%;
      width: 50%;
      background-color: white;
      border: none;
      height: 40px;
      border-radius: 3rem;
  }
  .container button{
      background-color: #002;
      color: white;
      width: 25%;
      border-radius: 4px;
      margin-bottom: 5%;
      padding: 2%;
      cursor: pointer;
  }
  .container a{
      color: #000;
      font-weight: bold;
      font-size: 14px;
  }

</style>


{% endblock %}

usuarios/templates/usuarios/configurar.html
{% load static %}

{% block content %}
<h2>Editar Perfil</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
        <label for="id_logotipo">Logotipo:</label>
        {{ form.logotipo }}
    </div>

    {% if config.logotipo %}
        <div>
            <p>Imagem atual:</p>
            <img src="{{ config.logotipo.url }}" alt="Logotipo" style="max-width: 150px;">
        </div>
    {% endif %}
    <button type="submit">Salvar alterações</button>
</form>
{% endblock %}

usuarios/templates/usuarios/editar_usuario.html
<h2>Editar Usuário</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Salvar</button>
</form>

usuarios/templates/usuarios/index.html
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PMO</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #F0FAFF;
        }

        header {
            display: flex;
            justify-content: center;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        header img {
            padding: 20px;
            animation: pulse 2s infinite ease-in-out;
        }

        .cabecario {
            margin-left: 4%;
        }

        @keyframes pulse {
            0% {
                transform: scale(1);
            }

            50% {
                transform: scale(1.2);
                /* Aumenta 20% */
            }

            100% {
                transform: scale(1);
                /* Volta ao normal */
            }
        }
    </style>
</head>

<body>
    <header>
        <img src="{% static 'logo.png' %}" alt="logotipo" >
    </header>
    <script>
        setTimeout(function () { window.location.href = "{% url 'login' %}" }, 7000)
    </script>

</body>

</html>

usuarios/templates/usuarios/login.html
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% load static %}
{% block content %}

  <div class="container">
    <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div>
      {{ form.username.label_tag }}<br>
      {{ form.username }}
    </div>
    <div>
      {{ form.password.label_tag }}<br>
      {{ form.password }}
    </div>
    <button type="submit">Entrar</button>
  </form>
  <p>Não tem uma conta? <a href="{% url 'cadastro' %}">Cadastre-se</a></p>
  </div>

<style>
  body{
    {% comment %} Coloca a imagem de fundo abaixo {% endcomment %}
    {% comment %} background-image: url(/static/background.png); {% endcomment %}
    background-size: 100%;
    background-repeat: no-repeat;
  }
  /*TELA AUTH LOGIN-REGISTRAR*/
  .container{
      text-align: center;
      background-color: white;
      border-radius: 4px;
      padding: 1%;
      margin-left: 30%;
      margin-top: 3%;
      width: 40%;
      padding-bottom: 3%;
      box-shadow: 0 0 5px black;
      background-color: rgba(0, 0, 0, 0.2);

  }
  .container h2{
      margin-bottom: 5%;
      margin-top: 10%;
      color: #002;
  }
  .container input{
      padding: 4px;
      margin: 1%;
      width: 50%;
      background-color: white;
      border: none;
      height: 40px;
      border-radius: 3rem;
  }
  .container button{
      background-color: #002;
      color: white;
      width: 25%;
      border-radius: 4px;
      margin-bottom: 5%;
      padding: 2%;
      cursor: pointer;
  }
  .container a{
      color: #000;
      font-weight: bold;
      font-size: 14px;
  }

</style>



{% endblock %}